### ISSUE TITLE
Usage pattern of: self.private.wallpapers.*

### ISSUE THREAD

**Issue by stratosgear** [bphenriques/dotfiles#60]
Hi,

I google landed on your repo trying to debug why I could not configure  my system to use the sddm-astronaut theme.

Browsing your repository I show the pattern of using the `self.private.wallapers` nixos incantation.

I am referring to this line: https://github.com/bphenriques/dotfiles/blob/2312aed26630ec1f3f36a3b844575f513d32da93/hosts/laptop/config.nix#L3

I am a new nixos user myself (a bit more  than a year of full time nixos usage on all my machines (4+)) and I would like to better understand a little more of the usage of that pattern.

From what I understand it seems that you have a private git repo (https://github.com/bphenriques/dotfiles-private) that you are using through this nix flake to pull in some things.  To clarify: I am NOT interested in the contents of your private repository.  I would just like to know a little more of how you have set it up so I can create something similar.  I completely recognize the need  to  do something similar (especially with assets like wallpapers, that you have already done) but I cannot imagine how you have done so.

Care to explain a bit the mechanics behind it? Or, do you have any links of how something like this has been setup, in case you followed a guide or something?

Thank you so much and sorry for the bother! :)

**Comment by bphenriques** [comment]
I giggled when you say "incantation" as it is how I see some stuff in Nix(OS) 😅 

The repo is sort-off in a weird state as I am migrating away from KDE to Niri (https://github.com/bphenriques/dotfiles/pull/58). That branch is more up to date but the `self.private.wallpapers` pattern still exists. I want to document it but haven't yet.

You are correct. It is a private repo mostly to avoid exposing wallpapers that I can't make public using the existing license. I don't have anything else in there but I could.

So it is a really small repo: 
```nix
{
  description = "bphenriques's private dotfiles for confidential (non-secret) information";
  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";

  outputs = inputs @ { self, nixpkgs, ... }: let
    lib = nixpkgs.lib;
    forAllSystems = lib.genAttrs [ "x86_64-linux" "x86_64-darwin" "aarch64-linux" "aarch64-darwin" ];
  in {
    packages = forAllSystems(system:
      let pkgs = nixpkgs.legacyPackages.${system}; in {
        wallpapers = pkgs.callPackage ./wallpapers.nix { };
      });
  };
}
```

`wallpapers.nix` just bundles images:
```nix
{ stdenv, lib, selected ? [ ] }:
let
  inherit (lib.strings) removeSuffix;
  fs = lib.fileset;
  basenameOf = fullname: (removeSuffix ".jpg" (removeSuffix ".png" fullname));
  filesToInclude = fs.fileFilter (file: (builtins.elem (basenameOf file.name) selected)) ./wallpapers;
in
stdenv.mkDerivation {
  name = "bphenriques-wallpapers";
  src = fs.toSource {
    root = ./wallpapers;
    fileset =
      if (selected == [])
      then ./wallpapers
      else (fs.intersection ./wallpapers filesToInclude);
  };
  postInstall = ''
    mkdir -pv $out/share/wallpapers
    cp -rv . $out/share/wallpapers
  '';
}
```

The `wallpapers` folder contains a bunch of `jpg/png/jpeg` files. This tutorial helped me at the time: https://nix.dev/tutorials/working-with-local-files.html

Then you can check the output using:
```
$ nix build .#wallpapers
$ nix path-info .#wallpapers
```

Assuming your `$PWD` is set to the repo.

<img width="1002" alt="Image" src="https://github.com/user-attachments/assets/cb31726d-9b1c-40c0-b4f2-5e28e9e50cab" />

Then, it just a matter of bringing that `dotfiles-private` repo dependency on your flake and use the existing output `packages.wallpapers` output. In my dotfiles, I added a prefix `self` ([source](https://github.com/bphenriques/dotfiles/blob/2312aed26630ec1f3f36a3b844575f513d32da93/lib/hosts.nix#L23)) and pass it as `extraArgs` when building nixos/darwin/home-manager. But you can also use `overlays` which IMHO is less intuitive (opinions differ). I like the `self` approach as the `dotfiles-private` repo is an extension of `dotfiles`.

Then you can refer to them with:
```nix
let
  wallpapers = self.private.wallpapers.override {
    selected = [ "lake-fishing-sunset" "mountains" "whale-sunset" "watch-tower" ];
  };
in
{
...

  `${wallpapers}/share/wallpapers/watch-tower.png`
}
```

The `override` is optional. I am doing this to avoid downloading all the images inside.

**Comment by bphenriques** [comment]
> Or, do you have any links of how something like this has been setup, in case you followed a guide or something?

It hasn't been easy at times but I have been working with my `dotfiles` using Nix for a long time (2 years maybe?). I try find things out on-need basis, otherwise it is overwhelming. Similar to you, I search for stuff on Github using `language:nix` filter and then I try to understand what is going on.

The `dotfiles-private` case is one that I did on my own. Before I was encrypting the files locally but it was very flaky as the Nix required them on-build time. I moved to a separate private repository and then I had to learn how to package plain files. The tutorial I sent is a good one. I then kept iterating on the package using `nix build` until I was happy with it. It is a bit tricky at times, therefore I suggest keeping things small and working to give you motivation to keep building what you need

**Comment by bphenriques** [comment]
Oh, I dont like the current way it is packaged. Would like to use `self.pkgs.wallpapers.{name}` but the problem is that each image has different extensions

**Comment by stratosgear** [comment]
Hi thanks for the very detailed answer.

Do not have the time right now to implement it, but I look forward to give it a crack.  I might have some further comments when I get to it.  What you gave so far makes sense!

If you're up for more giggles, based on your very detailed reply, the first quote that came to my mind about you was: "He's a good man. And thorough..." :) 🎳 

Thanks again!

**Comment by bphenriques** [comment]
Closing this for now :)

Feel free to reach out if you have questions.

I moved away from `self.private.wallpapers` and I just merged it with `self.pkgs`:
```nix
{ 

   ...
   specialArgs = {
    ...
    self = {
      pkgs = inputs.self.packages.${system} // inputs.dotfiles-private.packages.${system};
    };
    ...
  };
  ...
}
```

**Comment by stratosgear** [comment]
Hey, sorry for bothering you again...

I finally got the time to try my luck around implementing your private repo trick.

Unfortunately I am getting a series of errors:

``` 
✗  nix build .#wallpapers
error: cannot find flake 'flake:wallpapers' in the flake registries
 
✗  nix build .
error: flake 'git+file:///projects/stratosgear/ultragear-assets' does not provide attribute 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'
```

It feels like my flake.nix is missing something related on not defining my system (x86_64-linux, btw) maybe...?  Googling around did not yield anything... :(

I have my repo public (for the time being) if you want to have a look on what I've done: 

https://gitlab.com/stratosgear/ultragear-assets

Thanks once again!

**Comment by stratosgear** [comment]
Short update!

I was able to get `nix build .` but I still cannot build with `nix build .#wallpapers` like you did (I was missing a 'default' definition, that I have now added.

BTW, my problem is now how I would be able to build more than one packages in the same flake (I am trying `wallpapers`, like you, but I added an additional one, called `assets`, for other large binary files).  I just can't make `nix build .#whatever` to build.

If you have any suggestions, they are welcome.  Otherwise just ignore me!!! :)

**Comment by stratosgear** [comment]
Apologies!

Issue resolved.  I was randomly trying different invocations of the `nix build` command until came across the fact, that on zsh, apparently `.#somePackage` means something special. 

The proper way to build in zsh would be:

`nix build ".#wallpapers"`

which seems to work correctly (as `nix build ".#assets"`, too)

Once again, apologies for the "noise" here!

**Comment by bphenriques** [comment]
😆  no worries! Writing is a way of structuring our thinking and glad it worked for you!

**Comment by bphenriques** [comment]
Yeah, I like the pattern of having a private flake as this one. As I said before, I opted out of using `self.private.packages` to just use `self.packages` (where `self` is the flake definition).

**Comment by stratosgear** [comment]
I succesfully implemented your "pattern" from above, but I'm facing a weird issue...

The assets (wallpapers in this case) are under the /nix/store and they are owned by `root:root`.

Which means that certain apps (wpaperd for example) has issues reading them. Maybe because I am using home-manager to install many (most?) of my services/apps.

Is this something that you faced? Or maybe a suggestion on how to attack this problem...?

**Comment by bphenriques** [comment]
Oh, interesting. I personally never faced the issue. I use `swww` which runs as user service. The files are owned by `root:root` as well. This is a issue unrelated to the pattern but to something nix related.

What is the error?

**Comment by stratosgear** [comment]
OK, I got what I needed! :)

Meaning that the behavior is exactly the same for you and that you see that the files are owned by `root:root`, or if you had identified the issue and you had done any other tricks to overcome it!

But the plot thickens: (no idea if you find this interesting at all, but since we became "gitfriends" I'll share anyways)

wpaperd complains with:

```
➜  wpaperd -v
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
WARN [wpaperd::image_loader]
   0: Failed to read image "/nix/store/3hghva20r9vy9psspn46xkaqj0957577-ultragear-assets/share/assets/wallpapers/1-FHD.png" needed for HDMI-A-1
   1: Format error decoding Png: Invalid PNG signature.
   2: Invalid PNG signature.
```

which is weird.  Checking the .png image I see:

```
✗  file /nix/store/3hghva20r9vy9psspn46xkaqj0957577-ultragear-assets/share/assets/wallpapers/1-FHD.png
/nix/store/3hghva20r9vy9psspn46xkaqj0957577-ultragear-assets/share/assets/wallpapers/1-FHD.png: ASCII text
```
which is even weirder, until I:

```
➜  cat /nix/store/3hghva20r9vy9psspn46xkaqj0957577-ultragear-assets/share/assets/wallpapers/1-FHD.png
version https://git-lfs.github.com/spec/v1
oid sha256:cf3d70be7f5d387bcb4b85eacab0224dfdb2ab71d282572bcc42a2943d48eeab
size 4442408
```

which makes sense!

I use LFS for large binary files in my assets private repo, which is NOT supported by flakes checkout:
https://github.com/NixOS/nix/pull/10153

This has nothing to do with the `root:root` ownership I mentioned above, but I am sure that if I solve the LFS issue, this will wait for me to further debug later on (or lead me into another rabbit hole)

In any case, sorry for using you as a rubber duck. Thanks for your patience.



I do not want you to do any debugging for me, the issue is clear, but that rabbit hole (like every other one that I have fallen into) deepens!

**Comment by bphenriques** [comment]
TIL!

Thank you gitfriend!
